package za.co.neroland.nerospace.village;

import com.mojang.serialization.MapCodec;

import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.BaseEntityBlock;
import net.minecraft.world.level.block.RenderShape;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;

/**
 * Village Core (ALIEN_VILLAGERS_DESIGN.md §4.1) — the controller block at the heart of an alien
 * village. Generated by the hamlet feature; the player claims it by right-clicking.
 *
 * <p>Phase 3: claiming records the owner and is the anchor the later phases build on — it will hold
 * the per-village reputation map, owned plots, build queue and construction stockpile (Phase 4), and
 * tick the teach-and-grow loop. For now it is a claimable marker with a status readout.
 */
public class VillageCoreBlock extends BaseEntityBlock {

    public static final MapCodec<VillageCoreBlock> CODEC = simpleCodec(VillageCoreBlock::new);

    public VillageCoreBlock(Properties properties) {
        super(properties);
    }

    @Override
    protected MapCodec<VillageCoreBlock> codec() {
        return CODEC;
    }

    @Override
    protected RenderShape getRenderShape(BlockState state) {
        return RenderShape.MODEL;
    }

    @Override
    public BlockEntity newBlockEntity(BlockPos pos, BlockState state) {
        return new VillageCoreBlockEntity(pos, state);
    }

    @Override
    protected InteractionResult useWithoutItem(BlockState state, Level level, BlockPos pos, Player player,
            BlockHitResult hit) {
        if (!(level.getBlockEntity(pos) instanceof VillageCoreBlockEntity core)) {
            return InteractionResult.PASS;
        }
        if (level.isClientSide()) {
            return InteractionResult.SUCCESS;
        }
        if (!core.isClaimed()) {
            core.claim(player);
            player.sendSystemMessage(Component.translatable("message.nerospace.village_core.claimed"));
        } else if (core.isOwner(player)) {
            player.sendSystemMessage(Component.translatable("message.nerospace.village_core.status_self"));
        } else {
            player.sendSystemMessage(Component.translatable("message.nerospace.village_core.owned",
                    core.getOwnerName()));
        }
        return InteractionResult.SUCCESS;
    }
}
